### ISSUE TITLE
Update for compatibility with jQuery 3.5.1

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-nivo-slider#11]
oik-nivo-slider uses jQuery, using functions implemented by oik to enqueue the jQuery.
The jQuery delivered by oik-nivo-sider needs to be updated to cater for deprecations in jQuery 3.5.1
as indicated by JQMIGRATE messages in the console.

JQMIGRATE: jQuery.fn.resize() event shorthand is deprecated
JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.fn.hover() is deprecated
JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css

**Comment by bobbingwide** [comment]
The source code for Nivo Slider for jQuery is at https://github.com/Codeinwp/Nivo-Slider-jQuery
The project is actively looking for contributors.
I'm not sure how to build the `pack.js` versions of my `.js` files.
Ditto for my `.css` files
Perhaps it's time to update to use npm to do this.

**Comment by bobbingwide** [comment]
Once I started changing the jQuery code I discovered more deprecated logic in `jquery.oik-nc-click.js`.

**Comment by bobbingwide** [comment]
> I'm not sure how to build the `pack.js` versions of my `.js` files.
> Ditto for my `.css` files
> Perhaps it's time to update to use npm to do this.

7 years ago I wrote a routine called `minify.bat` that ran yuicompressor-2.4.7  against a number of files in oik
Either I should dust it off or find a more up to date solution.

**Comment by bobbingwide** [comment]
I've tried `yuicompressor-2.4.8`. 
It produced a load of messages with the `-v` option. e.g.
```
[WARNING] in jquery.nivo.slider-32.js
  Try to use a single 'var' statement per scope.
fn.nivoSlider.defaults,options); ---> var  <--- vars={currentSlide:0,currentImage:""
```
For oik's files it also produced these Warnings and even Errors.

I think I'd prefer to use the solution that's used in WordPress core.  ... If only I could find out what this is.

**Comment by bobbingwide** [comment]
> I've tried yuicompressor-2.4.8.

I created a new issue in oik-zip so that I'd have a solution for all my plugins. https://github.com/bobbingwide/oik-zip/issues/5

**Comment by bobbingwide** [comment]
> I think I'd prefer to use the solution that's used in WordPress core. ... If only I could find out what this is.

Again, see https://github.com/bobbingwide/oik-zip/issues/5

**Comment by bobbingwide** [comment]
The default271 theme uses `jquery.nivo.slider-271.js` or the .min version. It requires jQuery migrate to run in WordPress 5.5.1
It doesn't work with jQuery 3.5.1


Test jQuery updates settings | Works?
------------------------------- | --------
WordPress jQuery: 1.12.4, Migrate: not available, UI: 1.11.4 | No - Uncaught TypeError: $(..).live is not a function
WordPress jQuery: 1.12.4, Migrate: 1.4.1, UI: 1.11.4 | Yes
WordPress jQuery: 3.5.1, Migrate: not available, UI: 1.11.4 | No 
WordPress jQuery: 3.5.1, Migrate: 3.3.0, UI: 1.11.4 | No

```
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: jQuery.isFunction() is deprecated
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: jQuery.fn.hover() is deprecated
jquery.nivo.slider-271.js?ver=5.5.1:143 Uncaught TypeError: $(...).live is not a function
    at new NivoSlider271 (jquery.nivo.slider-271.js?ver=5.5.1:143)
    at HTMLDivElement.<anonymous> (jquery.nivo.slider-271.js?ver=5.5.1:655)
    at Function.each (jquery-3.5.1.js?ver=3.5.1:381)
    at jQuery.fn.init.each (jquery-3.5.1.js?ver=3.5.1:203)
    at jQuery.fn.init.$.fn.nivoSlider271 (jquery.nivo.slider-271.js?ver=5.5.1:650)
    at (index):509
    at dispatch (jquery-3.5.1.js?ver=3.5.1:5429)
    at elemData.handle (jquery-3.5.1.js?ver=3.5.1:5233)
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
jquery-migrate-3.3.0.js?ver=3.3.0:100 JQMIGRATE: jQuery.fn.bind() is deprecated
```

Is it worth fixing?
Well, most of the JQMIGRATE messages come from core.min.js, tooltip.min.js

**Comment by bobbingwide** [comment]
delivered in v1.16.0
